# Generated by Django 2.0.3 on 2018-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('SellerSKU', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ASIN', models.CharField(max_length=50, null=True)),
                ('InStockSupplyQuantity', models.IntegerField(null=True)),
                ('Condition', models.CharField(max_length=50, null=True)),
                ('MarketplaceId', models.CharField(max_length=50, null=True)),
                ('RequestId', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmazonOrderId', models.CharField(max_length=50)),
                ('SellerSKU', models.CharField(max_length=50)),
                ('ASIN', models.CharField(max_length=50, null=True)),
                ('QuantityOrdered', models.IntegerField(default=-1, null=True)),
                ('ConditionId', models.CharField(max_length=10, null=True)),
                ('IsGift', models.CharField(max_length=10, null=True)),
                ('ItemPrice', models.FloatField(null=True)),
                ('CurrencyCode_IP', models.CharField(max_length=10, null=True)),
                ('RequestId', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'orderitems',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmazonOrderId', models.CharField(max_length=50)),
                ('Seller', models.CharField(max_length=100, null=True)),
                ('LastUpdateDate', models.DateTimeField()),
                ('PurchaseDate', models.DateTimeField(default=None, null=True)),
                ('PaidDate', models.DateTimeField(default=None, null=True)),
                ('Amount', models.FloatField(max_length=10, null=True)),
                ('CurrencyCode', models.CharField(max_length=10, null=True)),
                ('OrderType', models.CharField(max_length=50, null=True)),
                ('OrderStatus', models.CharField(max_length=50, null=True)),
                ('SalesChannel', models.CharField(max_length=100, null=True)),
                ('NumberOfItemsShipped', models.IntegerField(null=True)),
                ('NumberOfItemsUnshipped', models.IntegerField(null=True)),
                ('BuyerEmail', models.CharField(max_length=100, null=True)),
                ('BuyerName', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('CountryCode', models.CharField(max_length=50, null=True)),
                ('StateOrRegion', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('PostalCode', models.CharField(max_length=50, null=True)),
                ('AddressLine1', models.CharField(max_length=500, null=True)),
                ('AddressLine2', models.CharField(max_length=500, null=True)),
                ('EarliestShipDate', models.DateTimeField(default=None, null=True)),
                ('LatestShipDate', models.DateTimeField(default=None, null=True)),
                ('LatestDeliveryDate', models.DateTimeField(default=None, null=True)),
                ('EarliestDeliveryDate', models.DateTimeField(default=None, null=True)),
                ('ShipServiceLevel', models.CharField(max_length=100, null=True)),
                ('ShipmentServiceLevelCategory', models.CharField(max_length=100, null=True)),
                ('ShippedByAmazonTFM', models.CharField(max_length=100, null=True)),
                ('MarketplaceId', models.CharField(max_length=100, null=True)),
                ('IsPrime', models.CharField(max_length=100, null=True)),
                ('IsPremiumOrder', models.CharField(max_length=100, null=True)),
                ('IsBusinessOrder', models.CharField(max_length=100, null=True)),
                ('IsReplacementOrder', models.CharField(max_length=100, null=True)),
                ('PaymentMethod', models.CharField(max_length=100, null=True)),
                ('PaymentMethodDetail', models.CharField(max_length=100, null=True)),
                ('FulfillmentChannel', models.CharField(max_length=100, null=True)),
                ('SellerOrderId', models.CharField(max_length=100, null=True)),
                ('RequestId', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('AmazonOrderId', 'LastUpdateDate')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('AmazonOrderId', 'SellerSKU')},
        ),
    ]
